# Generated by Django 6.0.6 on 2026-06-23 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('programs', '0001_initial'),
        ('universities', '0003_alter_university_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('offer_response_at', models.DateTimeField(blank=True, null=True)),
                ('admission_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.admissioncycle')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='identity.applicant')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='identity.universitystaff')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=50, null=True)),
                ('to_status', models.CharField(max_length=50)),
                ('changed_by_type', models.CharField(choices=[('applicant', 'Applicant'), ('university_staff', 'University Staff'), ('system', 'System')], max_length=50)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admissions.application')),
            ],
            options={
                'verbose_name_plural': 'Application status histories',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['university', 'status'], name='admissions__univers_b2196c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='admissions__applica_7e8475_idx'),
        ),
    ]
