# Generated by Django 6.0.6 on 2026-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='changed_by_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
