# Generated by Django 6.0.6 on 2026-06-26 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0003_alter_university_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('applicant', 'Applicant'), ('university_staff', 'University Staff'), ('platform_admin', 'Platform Admin'), ('system', 'System')], max_length=50)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField()),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Audit log entries',
                'indexes': [models.Index(fields=['university', 'created_at'], name='audit_audit_univers_ff640c_idx')],
            },
        ),
    ]
