# Generated by Django 6.0.6 on 2026-06-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Audit log entries'},
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='actor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
