# Generated by Django 6.0.6 on 2026-06-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
    ]
