#!/usr/bin/env bash
set -e
source "$(cd "$(dirname "$0")/.." && pwd)/env.sh"
source "$(cd "$(dirname "$0")/.." && pwd)/setup.sh"
source "$QA_DIR/lib.sh"

header "Browser: Manual QA Checklist"
echo ""
echo "  Run these tests manually in the browser because they require"
echo "  JavaScript rendering, file downloads, or visual verification."
echo ""
echo "================================================================"
echo "  STUDENT FLOW"
echo "================================================================"
echo "  1. Open http://localhost:3000"
echo "  2. Click 'Register' — fill form, submit"
echo "  3. Check console for verification email (EMAIL_BACKEND=console)"
echo "  4. Click verification link in console output"
echo "  5. Log in with registered credentials"
echo "  6. Browse programs (should see published programs)"
echo "  7. Click 'Apply' on a program"
echo "  8. Fill application form, save as draft"
echo "  9. Upload documents (transcript, passport, etc.)"
echo "  10. Submit application — should fail until docs uploaded + payment"
echo "  11. Complete payment (Stripe test card: 4242 4242 4242 4242)"
echo "  12. Submit application again — should succeed"
echo "  13. Check dashboard for submitted application status"
echo ""
echo "================================================================"
echo "  STAFF FLOW"
echo "================================================================"
echo "  1. Log in as UniversityStaff"
echo "  2. Navigate to Review Queue (Applications link in nav)"
echo "  3. Filter applications by status, program, cycle"
echo "  4. Click on an application to review"
echo "  5. Verify documents (click Verify button)"
echo "  6. Flag a document with reason"
echo "  7. Issue decision (admit/reject/waitlist)"
echo "  8. Check that decision button disabled when docs not all verified"
echo "  9. Reverse a decision (Admin only)"
echo "  10. View audit log"
echo ""
echo "================================================================"
echo "  ADMIN FLOW"
echo "================================================================"
echo "  1. Log in as PlatformAdmin"
echo "  2. Navigate to Admin area"
echo "  3. View universities"
echo "  4. View stats, users"
echo "  5. Deactivate a user"
echo ""
echo "================================================================"
echo "  EDGE CASES"
echo "================================================================"
echo "  - Deactivated user login → should show 'Account is deactivated'"
echo "  - Cross-tenant access → should not show other universities' data"
echo "  - Accepted application → status change should be blocked"
echo "  - Past deadline payment → should be rejected"
echo "  - MFA verification → staff must complete MFA before admin actions"
echo "================================================================"
echo "  SPRINT 11 — EDGE CASES (US-A-04, US-A-05, US-A-06, US-U-02)"
echo "================================================================"
echo "  US-A-04: Open two browser tabs editing the same draft"
echo "    → Both save; last write wins (no error, no data loss)"
echo "  US-A-05: Upload a file larger than 10MB"
echo "    → Should see 'File exceeds the maximum size of 10MB' error"
echo "  US-A-05: Re-upload a flagged document"
echo "    → Document status resets from 'flagged' to 'pending'"
echo "  US-A-06: Abandon payment (close browser without completing)"
echo "    → Application remains in 'draft' state"
echo "  US-U-02: Submit application after cycle closes"
echo "    → Should see 'The admission cycle is closed' error"
echo ""
echo "  When each checklist item is complete, note it here:"
echo "  _________________________________________________"
echo ""
pass "Browser checklist generated"

# Count this as a pass since the checklist was printed
PASSED=$((PASSED + 1))
